// ADMIN TYPES
export const FETCH_ALL_USER_REQUEST = "FETCH_ALL_USER_REQUEST";
export const FETCH_ALL_USER_SUCCEEDED = "FETCH_ALL_USER_SUCCEEDED";

export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCEEDED = "FETCH_POST_SUCCEEDED";

export const FETCH_SINGLE_POST_REQUEST = "FETCH_SINGLE_POST_REQUEST";
export const FETCH_SINGLE_POST_SUCCEEDED = "FETCH_SINGLE_POST_SUCCEEDED";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCEDED = "ADD_POST_SUCCEDED";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCEDED = "EDIT_POST_SUCCEDED";

export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCEEDED = "UPLOAD_IMAGE_SUCCEEDED";

export const CLEAR_SINGLE_ITEM = "CLEAR_SINGLE_ITEM";

// SITE TYPES
export const FETCH_BLOG_REQUEST = "FETCH_BLOG_REQUEST";
export const FETCH_BLOG_SUCCEEDED = "FETCH_BLOG_SUCCEEDED";

export const FETCH_BLOG_BY_SLUG_REQUEST = "FETCH_BLOG_BY_SLUG_REQUEST";
export const FETCH_BLOG_BY_SLUG_SUCCEEDED = "FETCH_BLOG_BY_SLUG_SUCCEEDED";

export const GET_POST_LIST_LENGTH = "GET_POST_LIST_LENGTH";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCEEDED = "POST_COMMENT_SUCCEEDED";

// AUTH TYPES
export const LOGIN_USER_REUQUEST = "LOGIN_USER_REUQUEST";

export const REGISTER_USER_REUQUEST = "REGISTER_USER_REUQUEST";

export const CHECK_AUTHENTICATION_REQUEST = "CHECK_AUTHENTICATION_REQUEST";
export const CHECK_AUTHENTICATION_SUCCEEDED = "CHECK_AUTHENTICATION_SUCCEEDED";
export const CHECK_AUTHENTICATION_FAILED = "CHECK_AUTHENTICATION_FAILED";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCEEDED = "GET_USER_SUCCEEDED";

// UTIL TYPES
export const LOADING_DATA = "LOADING_DATA";
export const LOADED_DATA = "LOADED_DATA";

// ERROR TYPES
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
